branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: null
global:
  application_name: csnlookup-flask-app
  branch: null
  default_ec2_keyname: aws-eb-csnlookup
  default_platform: python2.7
  default_region: eu-west-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
